"""
Script: Retirement / Closure Announcement Watcher (new, from the QED historical remap)

Per the QED history, retirement announcements reprice Cal-year futures on
the announcement date - months to years before the plant physically
closes (Yallourn's brought-forward 2028 retirement, Liddell's staged
exit). Eraring's closure timing is explicitly flagged in the build doc as
"the single biggest event risk for NSW forward prices", so this is worth
catching the moment AEMO publishes something about it, not waiting for
the next QED report.

Source: AEMO's Market_Notice feed (plain-text notices, one file per
notice, NOT the MMS CSV format everything else in this project uses).
This is a genuinely different kind of source: it's mostly high-volume
routine notices (~dozens/day of "PRICES CONFIRMED"/"PRICES UNCHANGED"
autogenerated notices), so this script keyword-filters the notice text
rather than alerting on everything, and tracks the last-processed notice
number so re-runs only look at new notices.

Scope note: this covers AEMO's own notice channel. It does NOT scrape
Origin Energy's ASX announcements page or any other company IR site -
company-level announcements sometimes land before AEMO's own notice, and
that's a real gap, but scraping a specific company's investor-relations
page is fragile (site-structure-dependent, breaks silently on redesigns)
and out of scope for this first build. Worth adding per-company ASX-feed
watching later if AEMO's own notice consistently lags the market-moving
announcement.
"""

from __future__ import annotations

import re
from datetime import datetime

import nemweb_common as nw

MARKET_NOTICE_URL = "https://www.nemweb.com.au/REPORTS/CURRENT/Market_Notice/"
NOTICE_FILE_PATTERN = r"MKTNOTICE_\d{8}\.R\d+$"

STATE_FILE = "closure_watcher_state.json"
MAX_FILES_PER_RUN = 300  # bounds a first-run catch-up; will work through any backlog over subsequent runs

CLOSURE_KEYWORDS = [
    "notice of closure", "closure of", "permanent closure", "cease generation",
    "cease to generate", "decommission", "withdraw from service", "retirement",
    "retire", "final closure", "de-registration", "deregistration",
]


def notice_number(url: str) -> int:
    m = re.search(r"\.R(\d+)$", url)
    return int(m.group(1)) if m else 0


def main() -> None:
    cfg = nw.CONFIG
    topic = cfg.get("ntfy_topics", {}).get("pasa", "pasa-alerts")  # low-frequency structural news, shares this topic

    files = nw.list_nemweb_files(MARKET_NOTICE_URL, NOTICE_FILE_PATTERN)
    if not files:
        print("[closure_watcher] No market notice files found.")
        return

    state = nw.read_state(STATE_FILE, default={"last_notice_number": 0})
    last_seen = state.get("last_notice_number", 0)

    new_files = [f for f in files if notice_number(f) > last_seen]
    if len(new_files) > MAX_FILES_PER_RUN:
        print(f"[closure_watcher] {len(new_files)} new notices - processing the most recent {MAX_FILES_PER_RUN} "
              "this run, will catch up on the rest next run.")
        new_files = new_files[-MAX_FILES_PER_RUN:]

    if not new_files:
        print("[closure_watcher] No new market notices since last run.")
        return

    matches = []
    highest_seen = last_seen
    for url in new_files:
        try:
            text = nw.download_bytes(url).decode("utf-8", errors="replace")
        except Exception as exc:
            print(f"[closure_watcher] WARNING: could not fetch {url}: {exc}")
            continue

        num = notice_number(url)
        highest_seen = max(highest_seen, num)

        lower = text.lower()
        if any(k in lower for k in CLOSURE_KEYWORDS):
            reason_start = text.find("Reason :")
            excerpt = text[reason_start:reason_start + 600].strip() if reason_start >= 0 else text[:600].strip()
            matches.append({"notice_id": num, "excerpt": excerpt})

    state["last_notice_number"] = highest_seen
    nw.write_state(STATE_FILE, state)

    if matches:
        # Persist every real match (not just push it) so other scripts can check "has a
        # closure notice ever actually mentioned plant X" - used by market_read.py's regional
        # outlook section to know when NSW/VIC's "coiled spring" (Eraring/Loy Yang A) calls
        # should flip from unpriced risk to "it happened."
        matched_log = nw.read_state("closure_watcher_matches.json", default=[])
        matched_log.extend({"notice_id": m["notice_id"], "excerpt": m["excerpt"],
                             "found_at": datetime.now().isoformat()} for m in matches)
        nw.write_state("closure_watcher_matches.json", matched_log)

    if not matches:
        print(f"[closure_watcher] Checked {len(new_files)} new notice(s), none matched closure/retirement keywords.")
        return

    lines = [f"Possible closure/retirement notice(s) - {len(matches)} match(es):"]
    for m in matches:
        lines.append(f"\n[Notice {m['notice_id']}]\n{m['excerpt']}")

    message = "\n".join(lines)
    print(message)

    nw.push_ntfy(
        topic=topic,
        title=f"Possible closure/retirement notice x{len(matches)}",
        message=message,
        priority="high",
        tags=["warning", "electric_plug"],
    )


if __name__ == "__main__":
    main()
